node {
    stage('Execute Shell Script') {
        // Use the sh step to execute the shell script
        sh '''
            #!/bin/bash
            echo "Hello-World"
            # Add your shell commands here
        '''
    }
}
