pipeline {
    agent any
    
    stages {
        stage('Execute Shell Script') {
            steps {
                // Use the sh step to execute the shell script
                sh '''
                    #!/bin/bash
                    echo "Hello-DevOps"
                    # Add your shell commands here
                '''
            }
        }
    }
}
