pipeline {
    agent {
        label 'Scipt_Slave'
        }

    stages {
        stage('Execute Shell Script') {
            steps {
                // Use the sh step to execute the shell script
                sh '''
                    #!/bin/bash
                    sleep 60
                    echo "Hello-DevOps"
                    # Add your shell commands here
                '''
            }
        }
    }
}
